import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/global.css";

import { ThemeProvider } from "@/components/feature/theme-toggle/theme-provider";
import { Header } from "@/components/layout/Header";
import { PageHeader } from "@/components/layout/PageHeader";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			suppressHydrationWarning
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Header />
					<div className="min-h-screen w-full font-sans">
						{children}
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
